# Generated by Django 5.0.6 on 2024-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movielist_movies_movie_actors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='movie',
        ),
        migrations.AddField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
